### ISSUE TITLE
mutli bundles and peerDependencies (state of 2018)

### ISSUE THREAD

**Issue by voronianski** [browserify/wzrd.in#193]
There was a thread about this several years ago (https://github.com/browserify/wzrd.in/issues/73) however I would like to start new discussion to think what we can do with current setup.

As far as I know: 

- wzrd.in runs with npm v6 now (https://github.com/browserify/wzrd.in/commit/e5f80b83f3c71723a313cff796aef434bd271d67)
- `/multi` bundles every dependency separately

Currently we have errors like this because `peerDependencies` are not installed:

```
---FLAGRANT SYSTEM ERROR---

--- error #0: ---


(logs uuid: a38dd810-e8ef-11e8-aaab-07d2929b7bb5 )

Error: "browserify exited with code 1"

code: 1
stderr: Error: Cannot find module 'react' from '/tmp/react-dom1181015-279-1woer41.gqqh/node_modules/react-dom/cjs'
    at /home/nowuser/src/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/home/nowuser/src/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/nowuser/src/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/home/nowuser/src/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/nowuser/src/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /home/nowuser/src/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)

dirPath: /tmp/react-dom1181015-279-1woer41.gqqh


------

This is probably an issue with the package, and not browserify-cdn itself.
If you feel differently, feel free to file a bug report at:

    https://github.com/browserify/wzrd.in/issues

Include the ENTIRETY of the contents of this message, and the maintainer(s)
can try to help you out.

Have a nice day!
```

### Example CURL request:

```bash
curl 'https://wzrd.now.sh/multi' -H 'pragma: no-cache' -H 'origin: http://localhost:9292' -H 'accept-encoding: gzip, deflate, br' -H 'accept-language: en-US,en;q=0.9' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3611.0 Safari/537.36' -H 'content-type: text/plain;charset=UTF-8' -H 'accept: */*' -H 'cache-control: no-cache' -H 'authority: wzrd.now.sh' -H 'referer: http://localhost:9292/index-dev.html?gist=b7e541a42c7c1218cad6' --data-binary '{"options":{"debug":true},"dependencies":{"react-dom":"16.6.3"}}' --compressed
```

**Comment by yunusozcan** [comment]
I use npm-install-peers package for solving the this problem. 

https://github.com/appitr/wzrd.in/commit/dfa6aa4fc0301dfb88cb30e4dce5c4f34e703ccf
